version: '3.8'

services:
  # 1. База даних PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: doc-classifier-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=doc_classifier
    ports:
      - "5433:5432" # Прокидаємо на 5433, щоб не конфліктувало з локальним Postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - doc-network

  # 2. Наш AI Сервіс (Python)
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: doc-classifier-ai
    ports:
      - "5001:5000"
    restart: always
    networks:
      - doc-network

  # 3. Наш Бекенд (Java Spring Boot)
  backend:
    platform: linux/amd64
    image: ghcr.io/shushpin/doc-classifier-backend:latest # <--- БЕРЕМО З ХМАРИ
    container_name: doc-classifier-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/doc_classifier
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - AI_SERVICE_URL=http://ai-service:5000/classify
    depends_on:
      - postgres
      - ai-service
    restart: always
    networks:
      - doc-network

# Створюємо ізольовану мережу для наших сервісів Watchtower (Автоматичне оновлення контейнерів)
  watchtower:
    platform: linux/amd64
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Даємо доступ до керування Docker'ом
    command: --interval 30 doc-classifier-backend # Перевіряти бекенд кожні 30 секунд
    restart: always
networks:
  doc-network:
    driver: bridge

# Зберігаємо дані БД навіть після видалення контейнера
volumes:
  db_data: