version: '3.8'

services:
  # 1. База даних PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: doc-classifier-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=doc_classifier
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - doc-network

  # 2. Наш AI Сервіс (Python)
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: doc-classifier-ai
    ports:
      - "5001:5000"
    restart: always
    networks:
      - doc-network

  # 3. Наш Бекенд (Java Spring Boot)
  backend:
    platform: linux/amd64
    image: ghcr.io/shushpin/doc-classifier-backend:latest
    container_name: doc-classifier-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/doc_classifier
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - AI_SERVICE_URL=http://ai-service:5000/classify
      - FILE_UPLOAD_DIR=/app/uploads
      # MICROSOFT OAUTH2 CONFIGURATION
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT_ID=${MS_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT_SECRET=${MS_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_SCOPE=openid,profile,email,User.Read
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_REDIRECT_URI={baseUrl}/login/oauth2/code/{registrationId}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT_NAME=LNU / Microsoft
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_AUTHORIZATION_GRANT_TYPE=authorization_code

      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MICROSOFT_AUTHORIZATION_URI=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MICROSOFT_TOKEN_URI=https://login.microsoftonline.com/common/oauth2/v2.0/token
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MICROSOFT_JWK_SET_URI=https://login.microsoftonline.com/common/discovery/v2.0/keys
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MICROSOFT_USER_NAME_ATTRIBUTE=email
    depends_on:
      - postgres
      - ai-service
    restart: always
    networks:
      - doc-network

  # 4. Watchtower (Автоматичне оновлення контейнерів)
  watchtower:
    platform: linux/amd64
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 doc-classifier-backend
    restart: always

# Створюємо ізольовану мережу для наших сервісів
networks:
  doc-network:
    driver: bridge

# Зберігаємо дані БД навіть після видалення контейнера
volumes:
  db_data: