version: '3.8'

services:
  # 1. База даних PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: doc-classifier-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=doc_classifier
    ports:
      - "5433:5432" # Прокидаємо на 5433, щоб не конфліктувало з локальним Postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - doc-network

  # 2. Наш AI Сервіс (Python)
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: doc-classifier-ai
    ports:
      - "5001:5000"
    restart: always
    networks:
      - doc-network

  # 3. Наш Бекенд (Java Spring Boot)
  backend:
    build:
      context: ./doc-classifier
      dockerfile: Dockerfile
    container_name: doc-classifier-backend
    ports:
      - "8080:8080"
    environment:
      # Вказуємо Spring Boot, де шукати базу даних (звертаємось по імені контейнера postgres)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/doc_classifier
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      # Вказуємо, де шукати AI сервіс
      - AI_SERVICE_URL=http://ai-service:5000/classify
      # Якщо треба, тут можна передати Microsoft Client ID/Secret
    depends_on:
      - postgres
      - ai-service
    restart: always
    networks:
      - doc-network

# Створюємо ізольовану мережу для наших сервісів
networks:
  doc-network:
    driver: bridge

# Зберігаємо дані БД навіть після видалення контейнера
volumes:
  db_data: